/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OurApproachRouteImport } from './routes/our-approach'
import { Route as IndexRouteImport } from './routes/index'

const OurApproachRoute = OurApproachRouteImport.update({
  id: '/our-approach',
  path: '/our-approach',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/our-approach': typeof OurApproachRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/our-approach': typeof OurApproachRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/our-approach': typeof OurApproachRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/our-approach'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/our-approach'
  id: '__root__' | '/' | '/our-approach'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OurApproachRoute: typeof OurApproachRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/our-approach': {
      id: '/our-approach'
      path: '/our-approach'
      fullPath: '/our-approach'
      preLoaderRoute: typeof OurApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OurApproachRoute: OurApproachRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
